apiVersion: kp.kpack.io/v1alpha3
kind: DependencyDescriptor
clusterStacks:
- name: demo-stack
  buildImage:
    image: harbor.ryanbaker.io/educates-demo-stack/build-demo-stack:latest
  runImage:
    image: harbor.ryanbaker.io/educates-demo-stack/run-demo-stack:latest
clusterBuilders:
- name: demo-cluster-builder
  clusterStack: demo-stack
  clusterStore: default
  order:
  - group:
    - id: tanzu-buildpacks/nginx
  - group:
    - id: tanzu-buildpacks/java-native-image
  - group:
    - id: tanzu-buildpacks/java
  - group:
    - id: paketo-buildpacks/procfile