apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: lab-markdown-sample
spec:
  portal:
    registration:
      type: anonymous
    updates:
      workshop: true
  workshops:
  - name: lab-markdown-sample
    capacity: 1
    expires: 60m
    orphaned: 5m
