apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: tanzu-build-service-overview
spec:
  portal:
    registration:
      type: anonymous
    updates:
      workshop: true
  workshops:
  - name: tanzu-build-service-overview
    capacity: 10
    expires: 90m
    orphaned: 15m
