apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: tanzu-build-service-overview
spec:
  title: Overview of Tanzu Build Service
  description: An overview of how the Tanzu Build Service can help you get from source code to containers in a repeatable and secure manner.
  vendor: eduk8s.io
  difficulty: beginner
  duration: 45m
  url: github.com/ryan-a-baker/educates-tbs
  environment:
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: $(workshop_namespace)-cluster-user
      rules:
      - apiGroups: ["apiextensions.k8s.io"]
        resources: ["customresourcedefinitions"]
        verbs: [ list, watch, get ]
      - apiGroups: [""]
        resources: ["persistentvolumes"]
        verbs: [ list, watch, get ]
  session:
    env:
      - name: ENV_HARBOR_PASSWORD
        value: changeme
  content:
    files: github.com/ryan-a-baker/educates-tbs
    image: theryanbaker/tbs-educates:latest
  session:
    namespaces:
      budget: x-large
      limits:
        default:
          cpu: 1000m
          memory: 1Gi
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: $(session_namespace)-cluster-user
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: $(workshop_namespace)-cluster-user
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: e2e-user
      rules:
      - apiGroups: [ e2e.tanzu.vmware.com, projectcontour.io ]
        resources: [ "*" ]
        verbs: [ get, list, watch, create, delete, patch, update ]
      - apiGroups: [ kpack.io ]
        resources: [ "*" ]
        verbs: [ get, list, watch, create, delete, patch, update ]
      - apiGroups: [ "*" ]
        resources: [ "*" ]
        verbs: [ get, list, watch ]
      - apiGroups: [""]
        resources: [ events ]
        verbs: [ create ]
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: e2e-user
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: e2e-user
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
    - apiVersion: e2e.tanzu.vmware.com/v1beta1
      kind: HarborProject
      metadata:
        name: $(session_namespace)
        annotations:
          training.eduk8s.io/objects.crd.scope: Namespaced
      spec:
        name: $(session_namespace)
    # - apiVersion: e2e.tanzu.vmware.com/v1beta1
    #   kind: ArgoCDProject
    #   metadata:
    #     name: $(session_namespace)
    #     annotations:
    #       training.eduk8s.io/objects.crd.scope: Namespaced
    #   spec:
    #     name: $(session_namespace)