apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-petclinic
spec:
  rules:
  - host: "{{ .Values.url }}"
    http:
      paths:
      - backend:
          service:
            name: spring-petclinic
            port:
              number: 80
        pathType: ImplementationSpecific