#@ load("@ytt:data", "data")
---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: metacontroller

#@ if data.values.psp.cluster_role:
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    namespace: metacontroller
    name: psp-rolebinding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: #@ data.values.psp.cluster_role
subjects:
    - kind: Group
      apiGroup: rbac.authorization.k8s.io
      name: system:authenticated
#@ end