#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name: controller-secrets
  namespace: harbor-project-controller
data:
  harbor_host: #@ base64.encode("harbor.{}".format(data.values.ingress.domain))
  harbor_username: YWRtaW4K
  harbor_password: #@ base64.encode(data.values.harbor.adminPassword)
